// Copyright 2021 The boltchat Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package identity

import (
	"fmt"
	"os"
	"path"

	"github.com/bolt-chat/client/config"
	"golang.org/x/crypto/openpgp"
	"golang.org/x/crypto/openpgp/packet"
)

func getEntitiesRoot() string {
	return path.Join(
		config.GetConfigRoot(),
		"entities",
	)
}

func getEntityLocation(username string) string {
	return path.Join(
		getEntitiesRoot(),
		fmt.Sprintf("%s.pgp", username),
	)
}

func writePGPEntity(username string, entity *openpgp.Entity) error {
	if _, statErr := os.Stat(getEntitiesRoot()); os.IsNotExist(statErr) {
		os.Mkdir(getEntitiesRoot(), 0700)
	}

	// Create entity file
	f, fileErr := os.Create(getEntityLocation(username))
	defer f.Close()

	// Only the current user may access this file
	f.Chmod(0600)

	if fileErr != nil {
		return fileErr
	}

	// Serialize the entity (including private key)
	return entity.SerializePrivate(f, &packet.Config{})
}

func createPGPEntity(username string) (*openpgp.Entity, error) {
	entity, entityErr := openpgp.NewEntity(
		username,
		"generated by Bolt",
		"identities@boltchat.net",
		&packet.Config{},
	)

	if entityErr != nil {
		return nil, entityErr
	}

	// Write the entity to disk
	writeErr := writePGPEntity(username, entity)
	if writeErr != nil {
		return nil, writeErr
	}

	return entity, nil
}

func loadPGPEntity(username string) (*openpgp.Entity, error) {
	f, openErr := os.Open(getEntityLocation(username))
	defer f.Close()

	if openErr != nil {
		return nil, openErr
	}

	pReader := packet.NewReader(f)
	entity, err := openpgp.ReadEntity(pReader)
	return entity, err
}
